export default [
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/25.png`,
    title: 'Tensorflow',
    price: '6',
    description: 'Développez votre projet machine learning avec Tensorflow',
    colors: [],
    new: true,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/26.png`,
    title: 'Python',
    price: '6',
    description: 'Développez vos projets informatiques en Python',
    colors: [],
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/27.png`,
    title: 'Java',
    price: '5',
    description: 'Développez vos applications en JAVA',
    colors: [],
    oldPrice: '23',
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/28.png`,
    title: 'C#',
    price: '1',
    description: 'Développez vos applications en C#',
    colors: [],
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/29.png`,
    title: 'Photoshop',
    price: '17',
    description: 'Développez vos compétences en Photoshop',
    colors: [],
    oldPrice: '23',
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/30.png`,
    title: 'Adobe Illustrator',
    price: '16',
    description: 'Développez vos compétences en Illustrator',
    colors: [],
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/31.png`,
    title: 'After Effect',
    price: '120',
    description: 'Développez vos compétences en After Effect',
    colors: [],
    new: true,
  },
  {
    src: `${process.env.PUBLIC_URL}/img/for_store/catalog/32.png`,
    title: 'Premiere Pro',
    price: '17',
    description: 'Développez vos compétences en Premiere Pro',
    colors: [],
    new: true,
  },
];
